import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/theme-provider";
import { Navbar } from "@/components/common/navbar";
import { PostHogProviderContext } from "@/contexts/posthogProvider";
import { GoogleTagManagerProvider } from "@/contexts/googleTagManager";
import CrispChat from "@/components/common/crispChat";  
import QueryClientProvider from "@/contexts/queryClientProvider";
import { AuthProvider } from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider defaultTheme="system" storageKey="theme">
          <QueryClientProvider>
            <AuthProvider>
              <PostHogProviderContext>
                <GoogleTagManagerProvider>
                  <Navbar />
                  {children}
                  <CrispChat />
                  </GoogleTagManagerProvider>
              </PostHogProviderContext>
            </AuthProvider>
          </QueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
